baseURL = 'https://phamminhtuangit.github.io/' # Sau n√†y thay b·∫±ng link GitHub c·ªßa b·∫°n
languageCode = 'vi'
title = 'Control & AI Lab'
theme = 'PaperMod'

[params]
  # T√πy ch·ªânh giao di·ªán
  defaultTheme = "auto" # T·ª± ƒë·ªông chuy·ªÉn Dark/Light mode
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true # N√∫t copy code ti·ªán l·ª£i

  # Profile hi·ªÉn th·ªã ·ªü trang ch·ªß
  [params.homeInfoParams]
    Title = "Hi there üëã, I'm Minh-Tuan Pham"
    Content = """
    Sinh vi√™n K67 - ƒêH B√°ch Khoa H√† N·ªôi (HUST).
    Major: Advanced Control | Deep Learning | Robotics.
    """

  # M·∫°ng x√£ h·ªôi (thay link c·ªßa b·∫°n v√†o)
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/PhamMinhTuanGit"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/tuanphamminh1708/"

  # K√≠ch ho·∫°t MathJax ƒë·ªÉ hi·ªÉn th·ªã c√¥ng th·ª©c to√°n h·ªçc (R·∫§T QUAN TR·ªåNG V·ªöI B·∫†N)
  [params.assets]
    disableHLJS = true